### ISSUE TITLE
Question about how to build .whl file.

### ISSUE THREAD

**Issue by ZhijingS** [hhhhpaaa/Mamba-ssm#1]
Thanks for sharing your solution! I wonder how to get the '.whl' file. After adding the "cc_flag.append("-gencode")
    cc_flag.append("arch=compute_60,code=sm_60")" into the setup.py, can I use “python setup.py bdist_wheel --dist-dir=/output” to get the '.whl' file? And do I have to build the '.whl' file using 1080ti GPU or can I use a more powerful GPU (like 3090) to accelerate the build?

**Comment by hhhhpaaa** [comment]
Hi, I have uploaded the detailed build steps in the build_step.pdf for reference. My build process is in an NVIDIA container. I'm not an expert in this area when it comes to NVIDIA CUDA builds. But as far as I can tell, for the '-gencode' flag, it is possible to build from a low version to a high version and (backwards compatible), i.e. build sm70 and above under a 10 series graphics card. Down-builds, such as building a Pascal architecture under ampere, have not been attempted (sm80 to sm60). As an extra note, the build speed is mostly dependent on the CPU threads, my build process took less than two hours on the 6 cores and 6 threads CPU and 1050ti.

**Comment by ZhijingS** [comment]
Thanks for your reply! With your guidance, I successfully build the latest version of mamba on 1080tiGPU. After completing the build of causal-conv1d and mamba-ssm, I also encountered the problem you mentioned \[here](https://github.com/state-spaces/mamba/issues/173). Following your method, I uninstalled _triton_ and then installed _triton_nightly-3.0.0. post20240716052845_ via **pip install -U --index-url https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/Triton-Nightly/pypi/simple/ triton-nightly**, and then successfully ran the test demos for causal_conv1d_fn, mamba, and mamba2. Thanks again for sharing this, I hope it helps more people.
