### ISSUE TITLE
The detected CUDA version (11.8) mismatches the version that was used to compile

### ISSUE THREAD

**Issue by Ronnie-Young** [hhhhpaaa/Mamba-ssm#2]
Hi, how do you solve this problem? I cannot use this command `MAMBA_FORCE_BUILD=TRUE python setup.py install` with cuda11.8 version. However once I switch to cuda12.1, it will uninstall the current torch and install 2.4.1 version automatically.

Attached some output details of the command line below:
```
RuntimeError:
      The detected CUDA version (11.8) mismatches the version that was used to compile
      PyTorch (12.1). Please make sure to use the same CUDA versions.
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for mamba_ssm
Failed to build mamba_ssm
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (mamba_ssm)
```

**Comment by hhhhpaaa** [comment]
Please check the CUDA version, compilation is best done in a container. It's important to make sure that the cuda version installed in the NVIDIA container matches the cuda version of Pytorch installed in the container. If CUDA is installed in a CONDA-isolated environment, there may be problems at compile time, especially if the CUDA in the virtual environment is different from the CUDA installed on the current system.

**Comment by Ronnie-Young** [comment]
Yes, I got up in the morning and retried it, and no error this time(I don't know why). But now I still get the following output, and I don't know why yet

```
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

Btw, maybe Pascal architecture GPUs cannot run mamba2 right? Cuz I got the following output when I run this command `lm_eval --model mamba_ssm --model_args pretrained=state-spaces/mamba2-130m --tasks lambada_openai,hellaswag,piqa,arc_easy,arc_challenge,winogrande,openbookqa --device cuda --batch_size 256` use your wheel files on a Tesla P100 GPU.

```
loc(fused["/home/ronnie_conda/.conda/envs/Mamba/lib/python3.10/site-packages/mamba_ssm/ops/triton/ssd_chunk_state.py":223:15, "/home/ronnie_conda/.conda/envs/Mamba/lib/python3.10/site-packages/mamba_ssm/ops/triton/ssd_chunk_state.py":223:25]): error: invalid element type in packLLEElements. Expected 'f32' but got 'f16'
loc(fused["/home/ronnie_conda/.conda/envs/Mamba/lib/python3.10/site-packages/mamba_ssm/ops/triton/ssd_chunk_state.py":223:15, "/home/ronnie_conda/.conda/envs/Mamba/lib/python3.10/site-packages/mamba_ssm/ops/triton/ssd_chunk_state.py":223:25]): error: 'llvm.intr.fmuladd' op requires the same type for all operands and results
Pass execution failedLLVM ERROR: Failed to translate TritonGPU to LLVM IR.
Aborted (core dumped)
```

**Comment by hhhhpaaa** [comment]
Yes, there are some issues with mamba2 on the Pascal architecture. On the Pascal architecture, mamba2 can be compiled successfully. At the time of testing, mamba2 can complete the inference, but when backpropagating, it prompts that Compute Capability>7.0 is required. I'm guessing it's the triton compilation part of mamba2 that is restricted, or maybe it's a triton version issue.
For the first error, you can look at the compilation log in detail. I previously uploaded a compiled version of 2.0 that does inference on Pascal architecture but backpropagation errors, but it works fine training and testing on Turing architecture (2080 ti). But for the second error, if you are performing an inference task, it may be that Triton has a problem, you can try to use Triton Nightly.

**Comment by Ronnie-Young** [comment]
OK, I tried it again today and not any problem. Maybe I have to buy a GPU with a newer architecture when I plan to use mamba2 later. Thank you so much!!
